### ISSUE TITLE
Please update the tag with latest commit

### ISSUE THREAD

**Issue by turc42** [Pramod-Devireddy/go-exprtk#3]
currently go get is pulling v1.0.0. This tag excludes the recent add of the Delete function. 

![Screen Shot 2022-02-08 at 10 04 22 AM](https://user-images.githubusercontent.com/5882786/153014401-a39b7a37-ba6a-4edb-bfcb-263279527e3b.png)

**Comment by Pramod-Devireddy** [comment]
updated.
